name: post-tests

on:
  workflow_dispatch:
  push:
    branches:
      - post_service

jobs:
  testing-post:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: post-service-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TEST_POSTGRES_DB: post-service-test
      POST_TESTING: True
      PYTHONPATH: ${{ github.workspace }}/services/post:$PYTHONPATH
      JWT_SECRET_KEY: very_secret_secret
    strategy:
      matrix:
        python-version: [ "3.12" ]
    defaults:
      run:
        shell: bash
        working-directory: services/post
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-req.txt

      - name: Migrate Test Database
        run: |
          alembic upgrade main@head
          alembic upgrade dangerous@head

      - name: Run tests
        run: |
          cd tests
          pytest
