name: user-tests

on:
  workflow_dispatch:
  push:
    branches:
      - user_service

jobs:
  testing-user:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user-service-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-service-test
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/services/user:${{ github.workspace }}/services/user/tests:$PYTHONPATH
      JWT_SECRET_KEY: very_secret_secret
    strategy:
      matrix:
        python-version: [ "3.12" ]
    defaults:
      run:
        shell: bash
        working-directory: services/user
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-req.txt

      - name: Migrate Test Database
        run: alembic upgrade test@head

      - name: Start Celery Worker
        shell: bash
        run: |
          celery -A src.celery_app worker --loglevel=info --detach
          sleep 3s

      - name: Run tests
        run: |
          cd tests
          pytest
